### ISSUE TITLE
[jellyfin] Error writing to cache directory

### ISSUE THREAD

**Issue by maxirus** [maxirus/helm-charts#3]
**Describe the bug**
Jellyfin is unable to write images to the /cache/temp directory. The system log is filled with errors like below:

```
[2020-03-31 00:06:44.382 +00:00] [ERR] [87] App: Error in "Dynamic Image Provider"
System.UnauthorizedAccessException: Access to the path '/cache/temp/*.jpg' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchToFileInternal(BaseItem item, IReadOnlyList`1 itemsWithImages, ImageType imageType, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Images.BaseDynamicImageProvider`1.FetchAsync(T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

**Version of Helm and Kubernetes**:
Kubernetes: `v1.17.2+k3s1`
Helm: `v3.0.2`

**Which chart**:
jellyfin:v0.2.0 -->

**What happened**:
The image file was not written to the /cache/temp directory

**What you expected to happen**:
File to be written to the /cache/temp directory and no errors in Logs

**How to reproduce it** (as minimally and precisely as possible):
Helm Chart settings:
```yaml
persistence.cache.enabled: true
podSecurityContext.fsGroup: 8675309
securityContext.runAsGroup: 8675309
```

Add media. Watch logs.

**Anything else we need to know**:

**Screenshots**

**Comment by maxirus** [comment]
May be due to [this](https://github.com/jellyfin/jellyfin/issues/2471) upstream issue.

**Comment by TKFRvisionOfficial** [comment]
Bump
Issue presists with version 10.7.5

```
[2021-06-06 16:58:39.881 +00:00] [ERR] [22] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "The Open Movie Database"
System.UnauthorizedAccessException: Access to the path '/cache/omdb/tt1628033_season_5.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Dispose(Boolean disposing)
   at Emby.Server.Implementations.Serialization.JsonSerializer.SerializeToFile(Object obj, String file)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureSeasonInfo(String seriesImdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.EnsureSeasonInfo(String seriesImdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.GetSeasonRootObject(String imdbId, Int32 seasonId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbProvider.FetchEpisodeData[T](MetadataResult`1 itemResult, Int32 episodeNumber, Int32 seasonNumber, String episodeImdbId, String seriesImdbId, String language, String country, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Omdb.OmdbEpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
